### PR TITLE
Merged automatons.py > grow_saplings.py, Rewrote to use callLater

### PR DESCRIPTION
**Pull request by hikari-no-yume**
Oh and also added start.sh for my personal, Linux convenience

Now it's "perfect" :D

### CODE REVIEW

**Comment by squiddy** [comment]
Whether or not the start script should be included should be discussed in a separate pull request (in my opinion). I suggest you remove the change from this pull request, it doesn't really belong in here. Makes the review easier too. Of course it's only a small change, but it's a good idea to keep things related anyway.

**Comment by hikari-no-yume** [comment]
squiddy: Please tell me how to do that. Github does not make it obvious, or maybe even possible.

**Comment by squiddy** [comment]
I don't know if GitHub offers that kind of functionality, I doubt it though. When I made an error, I just closed the request, changed my local branch and pushed it again to open a new pull request.

**Comment by hikari-no-yume** [comment]
Fixed.

**Pull request merged**
