### PR TITLE
Code quality enforcement

### PR DESCRIPTION
**Pull request by QualityBot**
## Code Quality Enforcement

I'm a bot that determines the most common coding styles in your project and attempts to make that style consistent across your whole repository.
### Change Summary
- Converted tabs to spaces
- Converted CRLF to LF
- Removed trailing newlines

[My Source Code](https://github.com/QualityEnforcer/QualityEnforcerBot) | [More Information](#) | [My Author](https://github.com/SirCmpwn)

If I did something wrong, or if you want more featues, pull requests are always welcome. This is an **automated tool**, and no human reviewed these changes. Please ensure that they are correct before merging. If they aren't, leaving an [issue](#) would be appriciated.

### CODE REVIEW

**Comment by MostAwesomeDude** [comment]
NAK:
- This is a PEP8 codebase.
  - Four spaces to the indent, not three.
  - Multiline statements need to have additional indentation.
- Trailing newlines at the ends of files are correct. Omitting them just means that they will come back when any sane tool edits the file again.

This diff is far too large; show me the diff of only converting tabs to spaces.

**Comment by ddevault** [comment]
Sane tools have a fake buffer extending past the end of the file.

As for spaces/indent, try explicitly stating your requirements in the issue body. Follow instructions in the README.

**Comment by squiddy** [comment]
> As for spaces/indent, try explicitly stating your requirements in the issue body. Follow instructions in the README.

I had to look at your bot's project to see what you're talking about. As far as I know, no one here created an issue for the bot in the first place, it just came here and dropped a huge diff. So now we should create an issue for it to do only what is necessary?

**Comment by ddevault** [comment]
MostAwesomeDude made the initial request. If you want it to, feel free to make another and explicitly state style guidelines.

**Comment by ddevault** [comment]
[Link to MostAwesomeDude's request](https://github.com/QualityEnforcer/QualityEnforcerBot/issues/18)

**Comment by squiddy** [comment]
Oh sorry, didn't know about that.

**Pull request closed without merging**
