### PR TITLE
Small fixes towards a simpler bravo.

### PR DESCRIPTION
**Pull request by JeppeKlitgaard**
Did some small fixes/finishing touches here and there.
# Summary:
- Moved tests out of **_bravo**_, and into main tree.
- Turned test packages into normal directories.
- Fixed 3 files not being executable when they really should have been.
- Removed unused and old code in **run_benchmarks.py**.
- Added 'total elapsed time' feature to **run_benchmarks.py**.
- Fixed these 3 PEP8 errors: E301, E302, E303. Many more remain, but I've been told autopep8'ing is bad :(
- Moved **_images/**_ to **_docs/images/**_.
- Added **_samples/**_, this will be used later on.

Hopefully these commits are of more use than my last ones, which turned out to be a total failure :(.

### CODE REVIEW

**Comment by MostAwesomeDude** [comment]
I would not say that your previous commits were a failure. I do apologize
for not being able to review them yet due to my job taking up my time.

One thing I'll note right now: tests absolutely should be shipped with
Bravo. It is important that people be able to test with:

$ trial bravo

If they can't, then the tests are broken.

**Comment by MostAwesomeDude** [comment]
I've gone over all of these commits and left comments. I can pull in all of the LGTMs immediately, if you're okay with rebasing.

**Comment by JeppeKlitgaard** [comment]
I'm afraid my git jargon is failing me, but sure! I am okay with _rebasing_.

**Comment by MostAwesomeDude** [comment]
Sorry for being so busy. I've cherry-picked the commits that looked good.

**Comment by MostAwesomeDude** [comment]
Closing this PR because all of the approved code has been cherry-picked already and there haven't been further updates.

@edunham: Feel free to salvage code from here if you like.

**Pull request closed without merging**
