### PR TITLE
Support paintings

### PR DESCRIPTION
**Pull request by squiddy**
Now player can place and remove paintings. One bigger remaining task is the check for the available space. Right now, a random painting is place, whether there is enough space or not. I'm working on that, but would appreciate some feedback on the basics now.

Most code is fairly simple and (I hope) readable. I just want to point out 2 more important changes.
1. In send_chunk of Protocol, I've removed the create (0x1E) packet. Paintings would not work with it, but it doesn't seem to be necessary. Pickups and paintings work fine. The wiki says "Most entity-related packets are subclasses of this packet.", so I guess this does apply at least to pickup and painting packages.
2. Paintings are entities, they are removed when a use (0x07) package is send. I have added a IUseHook for this.

### CODE REVIEW

**Comment by MostAwesomeDude** [comment]
From the initial description, I am worried about not sending "create". It has historically been absolutely necessary to keep the client from crashing or failing to render the target entity.

I'll take a deeper look at this later.

**Comment by squiddy** [comment]
Thanks for your feedback. All I can say is, the official server does not send "create" for paintings. At least the tcp dumps I did showed none.

**Comment by MostAwesomeDude** [comment]
I'm quite okay with the overall tone of this patchset, although there are a lot of things that have snuck in and that should definitely be split out. If making this work for 1.3 is a big concern, I can do the splitting and munging, but I figured that you might want a heads-up first.

**Comment by squiddy** [comment]
Appreciate that. I don't think we're in a hurry here getting this into 1.3. As you said, lots of stuff that should be split out, some things I wasn't even sure you'd agree with it. As of now, this can't be merged into master actually, it'll break because of the per-world config, but that's easily fixed. I'd prefer to polish this first, and I do have a suggestion for improving the placement of paintings (right now they don't consider available space).

Things that need to be split out (please correct me if I'm wrong here):
- Marking chunks dirty (world helper function)
- IUseHook, are you okay with this actually? I'm wary of this, I fear another hook may cause trouble, like we have with dig/build. On the other hand, those could be fixed once we get there.

**Comment by MostAwesomeDude** [comment]
IUseHook should probably announce which blocks or items it is used with, and then the caller can just make sure that it's only calling hooks which actually care. Order of operations should cease to matter at that point.

I'm quite okay with the world helper for marking chunks as dirty; it would simplify the automatons a bit.

**Comment by MostAwesomeDude** [comment]
Cherry-picking was necessary, but I've pulled this in. Sorry for the massive delay.

**Pull request closed without merging**
