### PR TITLE
Protocol 4 support added.

### PR DESCRIPTION
**Pull request by mathuin**
This started as "make bravo work with 1.7" and turned into "clean up bravo enough to make it posible to make bravo work wtih 1.7", so the changes are somewhat conflated.

It does work -- even partially supports encryption -- and almost all tests still pass.

### CODE REVIEW

**Comment by edunham** [comment]
Thank you! I made a develop branch and merged all of this in, then will merge back to master if I can get tests passing.

**Comment by justinnoah** [comment]
@mathuin looks like this was never merged....

Anyhow, if you can checkout this branch, and rebase with master to bring it up to speed, and add the missing dependencies to the requirements file (pycrypto and pyasn1), I'll gladly give it a one over and merge it

**Comment by mathuin** [comment]
Just in time for 1.8! :-) :-) I will work on this and get back to you ASAP.

**Comment by justinnoah** [comment]
Be sure to keep it at protocol netty4. we'll work on adding support for other protocols later.

**Pull request closed without merging**
