### PR TITLE
Fix player position

### PR DESCRIPTION
**Pull request by squiddy**
These changes will fix the position and orientation of a player when he spawns and those values will be saved correctly.

The first one corrects a minor mistake. When a player was loaded in BravoProtocol, his location was overridden by the protocol location, thus throwing away all changes that might have occured in the serializer.

The second one will reconstruct the orientation pitch from the player data correctly. The value is clamped between -PI/2 and PI/2 (-90° and 90° as the specification suggests). When clamped between 0° and 360° the rotation on the client was incorrect. I'm not sure if this is the right way to do this, the history of bravo/location.py suggest a possible link to tracks? I had to change location tests so they don't break, but I don't know if this might affect something else.

### CODE REVIEW

**Comment by squiddy** [comment]
Argh, just saw that other packets use orientation where pitch can be all 360°. Never mind the second commit then. Have to fix this for the player in some other way.

**Comment by MostAwesomeDude** [comment]
Okay, so I pushed a bunch of things. Have you any idea why the orientation is all weird now?

**Comment by squiddy** [comment]
I can't spot anything weird with orientation, how can I reproduce this error?

**Comment by MostAwesomeDude** [comment]
Maybe everything's good now? I'll close this since, if nothing else, these patches don't quite apply any more. The new code's a bit messy, but it does the job.

And yeah, tracks need a test or three, but they're really complex and I don't have mocks for entire worlds and chunks. (Yet.)

**Pull request closed without merging**
