### PR TITLE
Cleaner error when failing on plugin importing

### PR DESCRIPTION
**Pull request by justinnoah**
plugin: cleaner exception output. Uses interface.**name** instead of just interface.

### CODE REVIEW

**Comment by justinnoah** [comment]
I had the pull request point to my master. It happens to be a moving target, yay. OK so now, the pull request also includes the bed recipe.

**Comment by MostAwesomeDude** [comment]
Both look good. I'm not a fan of these dual-purpose merges, but I can live with it this time. :3

**Comment by justinnoah** [comment]
It's what happens when the pull request is set to master rather than a commit.

I can't really seporate commits. If I did them individually, there would be two requests with the first containing the first commit and the second containing the first and second commit.

if you know of a way to do it better, I am all ears!

**Comment by alucas** [comment]
uh what ?

Make 2 branch and create a pull request for each them.

**Pull request merged**
