### PR TITLE
Fix warp command

### PR DESCRIPTION
**Pull request by squiddy**
```
Due to the refactoring of serializers, world no longer has a folder
attribute. Use the one from the world serializer.
```

This makes the warp commands work again. But I'm unsure if this is the best solution. It seems not right to me, that the warp commands need rely on serializer's implementation to access the world's folder. What do you think?

### CODE REVIEW

**Comment by MostAwesomeDude** [comment]
They need to be persistent, so we should probably extend ISerializer to support them, right?

**Comment by squiddy** [comment]
So I guess it should be extended in a way that plugins have a common interface to store custom data? To get rid of file handles at all, and to be similar to the existing interface, I could think of two methods:

```
data = serializer.load_plugin_data(name)
serializer.save_plugin_data(name, data)
```

Warp works on the file handle directly, so this would complicate things. One could keep it simple, and just return a file-like object (handle to the opened file):

```
file_like = serializer.get_plugin_data(name)  # don't mind the name
```

**Comment by MostAwesomeDude** [comment]
Hmm. Warp's hardly sacred; it's pretty hax. I'd be okay with rewriting it to understand the new way of doing things.

From a serializer's POV, anything besides big, atomic writing and reading is going to suck, and giving file handles to plugins is iffy for two reasons:
1. It prevents serializers from syncing changes to disk while keeping file handles valid
2. It prevents serializers from being backed by anything besides file-like interfaces (e.g. SQL and noSQL solutions which hipsters seem to love so much these days)

Using a StringIO-ish indirection inside the serializer would solve both of these, but at that point, we should just put the onus on the plugin to do a StringIO or whatever they need. In this particular case, it'd be a win because StringoIO wouldn't be needed at all; we can just keep the data in memory directly most of the time and only serialize and deserialize on write and read respectively.

That's my opinion on this. I've noticed that, generally, most plugins don't store their own data, and they certainly don't do it in a standard way. I think Bukkit solves this, slightly, but I also think Bukkit is Doin' It Wrong, so.

**Comment by squiddy** [comment]
The possibility to switch serializer backends raises the question, how we handle more complex datastructures, if at all. Storing a plain string in a file or database row should be no problem, but what about nested structures? Should those be treated different, or just saved as a blob? Otherwise, this problem might be more hypothetical.

> because StringoIO wouldn't be needed at all; we can just keep the data in memory directly most
> of the time and only serialize and deserialize on write and read respectively

I have difficulties understanding what you mean here. Who's going to keep the data in memory? I've read this multiple times, but I probably miss your real point.

I've thrown together a prototype of a interface itself here (https://github.com/squiddy/bravo/commit/4849323c65aa6002117a0dc185fe536ae602e967), that provides the two basis operations, read (with a cache) and write. Maybe this helps to clear possible misunderstandings.

**Comment by MostAwesomeDude** [comment]
I am in favor of that commit and will merge it after fixing a handful of other things on the branch I'm working on.

**Comment by MostAwesomeDude** [comment]
NAKing this series in favor of the refactoring suggested by that new addition to ISerializer. Also merged 4849323c65aa6002117a0dc185fe536ae602e967, with an addon to remove the cache in favor of the filesystem's native cache.

**Pull request closed without merging**
