### PR TITLE
remote: Fix lighting of chunks populated by ampoule processes.

### PR DESCRIPTION
**Pull request by squiddy**
Just making sure this isn't forgotten.

### CODE REVIEW

**Comment by dbdii407** [comment]
Having no lighting issues. http://min.us/mvk1TXh

**Comment by squiddy** [comment]
And you do have ampoule activated? Also, this only affects new chunks, not ones loaded from disk.

To be honest, I haven't tried this today, but a few days ago, while fixing ampoule on Windows together with Varriount, this was a problem, even on linux. If one compares make_chunk in bravo/remote.py, and populate_chunk in bravo/world.py, this is what's missing, and what fixed it for me.

**Comment by dbdii407** [comment]
Yes I do. And you are correct, it only effects new chunks. As I logged back in to find this: http://min.us/mvpmXyE Although, something tells me this is a seperate issue?

**Comment by squiddy** [comment]
Fixed in https://github.com/MostAwesomeDude/bravo/commit/0b3ffd192c4a1313045e43e568c57e5b0d635d4d

@dbdii407 Yes, there are still minor issues with lighting.

**Pull request closed without merging**
