### PR TITLE
Code made pep8-complaint.

### PR DESCRIPTION
**Pull request by JeppeKlitgaard**
# Sorry

Right off the bat I would like to apologize for the numerous mistakes I've probably made in the pull-request part of this pull-request. It is my first, you see =)

I've done a bit of work on bravo, which sums up to:
- Made it more or less PEP8-compliant. Fixed about 1500 PEP8 errors. 406 remain, according to **_flake8**_
- Removed unused code in `run_benchmarks.py` (I think it was unused, you best check. I sure  couldn't find out what it was for.)
- Added a total elapsed time to `run_benchmarks.py`
- Made all .py files executable. (Note for some unknown reason, **_nosetests**_ don't run tests on executable files per default, to fix it simply add "--exe" to it.)

### CODE REVIEW

**Comment by MostAwesomeDude** [comment]
Hi! Thanks for contributing to Bravo.

Out of curiosity, why would we want all of the source code to be executable? Nothing in the main library has main functions or anything like that, and I'm not sure what's gained by doing this.

**Comment by JeppeKlitgaard** [comment]
If I'm quite honest, I don't really know, just seems more consistent to me, also most python editors seem to automatically make files executable (At least mine does, **_spyder**_), so for future commiters it might be nice.

I completely understand if you don't want the code PEP8'd/chmod'd, and I'd be fine with you turning down this pull-request, if you don't like it.

**Comment by JeppeKlitgaard** [comment]
Started refraction.

# Goals:
- More like vanilla MineCraft server/bukkit (In order to ease use for non-"export" users.)
- Simply install it, it will automaticly add itself to `usr/local/bin` as **_bravo.py**_. You just run bravo.py from command-line and it will act as a MineCraft server based in your current directory. (And making it look like a bukkit installation, with **_plugins/**_, **_banned-ips.txt**_, etc.)
- Generally just making it easier, smoother and so on.

**Comment by JeppeKlitgaard** [comment]
A few noob-mistakes, will work in seperate branch now :S

**Comment by JeppeKlitgaard** [comment]
Removed support or InfiniCraft, if someone wants it reintroduced, do it as a third-party module/plugin. Again, this was done to simplify/minify/remove redundancies.

**Comment by MostAwesomeDude** [comment]
This is _far_ too much stuff for this single pull request. I can (and probably will) pull in a couple pieces, but this is too much. Also please don't ask me to pull things that are broken, like 5f571bb; clean up your commits.

**Comment by JeppeKlitgaard** [comment]
Sorry, A bit of a newb with all this stuff, it seems when I push to my fork, it automatically gets put into this pull request etc, Thanks for your feedback tho! =)

Quick question, what is the `config_name` in https://github.com/bravoserver/bravo/blob/master/bravo/beta/protocol.py under BetaProxyProtocol, used for?

**Comment by JeppeKlitgaard** [comment]
Again, I did not mean for all this stuff to be put into one pull request, but it's getting automatically put here. Sorry about that.

**Comment by JeppeKlitgaard** [comment]
@MostAwesomeDude @TkTech 
I think I'll start over, hopefully I've learnt stuff from my numerous mistakes, sorry you had to witness it. And thanks once more for the feedback

**Comment by edunham** [comment]
@dkkline Looks like it's a "feature" that pull requests auto-add all ensuing commits. [GH help](https://help.github.com/articles/using-pull-requests) says "Pull requests can be sent from any branch or commit but it's recommended that a topic branch be used so that follow-up commits can be pushed to update the pull request if necessary."

The fix is to make each pull request's changes in a separate branch.

**Comment by JeppeKlitgaard** [comment]
Closed since I made just about a gazzillion mistakes, sorry for the bother.

Will make new pull-request, hopefully this one will be slightly more successful. Once again, sorry!

**Comment by edunham** [comment]
Don't apologize; everybody starts somewhere and you've learned a lot from this pull request. Thank you for working on Bravo!

**Comment by JeppeKlitgaard** [comment]
Made a new pull-request here: [New pull](https://github.com/bravoserver/bravo/pull/428). I implemented the stuff from this pull-request, properly this time.

**Pull request closed without merging**
