### PR TITLE
better lighting

### PR DESCRIPTION
**Pull request by matejcik**
pretty lights, with water dimming the light as it passes through

also i guess it's slower, because it now processes light for every block, not just at the highest point

plus fixed pack_nibbles and unpack_nibbles, and placing the player one block higher (otherwise it ends up drowned in a block below it)

### CODE REVIEW

**Comment by justinnoah** [comment]
Did you modify/test with unit tests?

**Comment by matejcik** [comment]
no, i'll do a new one

**Comment by matejcik** [comment]
ah, this thing adds commits by itself ... cool

**Comment by justinnoah** [comment]
matejcik it adds commits by itself if you have your commit range set to master for your fork since master is a moving target.

**Comment by MostAwesomeDude** [comment]
Cherry-picked the good ones.

**Pull request closed without merging**
