### PR TITLE
Fully working saplings automaton - Tracks saplings, random growth

### PR DESCRIPTION
**Pull request by hikari-no-yume**
- Added saplings automaton - Tracks saplings, random growth
- Small changes to terrain.trees.Tree
- Added to example ini (didn't add saplings to generators, just grow_saplings to automatons)

Known Issues: Currently discards sapling type (birch/normal/oak). Otherwise seems to work perfectly.

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
Fixed commits to be merged (amending first commit, fixing bit-shift issue, moved tree interface change to separate commit).

**Comment by espes** [comment]
Yeah you probably want to be using time.time() instead of time.clock()

**Comment by hikari-no-yume** [comment]
I don't get what's wrong with it. I get the current time, in seconds, add a random number of seconds, then check later if the current time is over that time.

Edit: Oh I see. Fixing.

**Comment by hikari-no-yume** [comment]
Rewrote history again (lol) and improved further. Testing reveals it works correctly.
Uses time(), and uses filter with a lambda to only process saplings which have "timed out" (that is, need to be updated).

**Pull request merged**
