### PR TITLE
New 1.8 Blocks

### PR DESCRIPTION
**Pull request by d4l3k**
These are the new 1.8 blocks that are in the client.

### CODE REVIEW

**Comment by MostAwesomeDude** [comment]
Hi,

As shown by the above commits, your patch was blatantly wrong. It also ignored commenting conventions. I understand that bravo.blocks is horribly confusing and needs a makeover badly, but this is the last time I'm merging your patches as long as you aren't testing them.

**Comment by d4l3k** [comment]
I'm sorry about that. I just made those changes so I could mess around with the new blocks and thought I would push it to help others. It's also the first time I've submitted a patch.

**Comment by MostAwesomeDude** [comment]
It's alright. A couple other people pointed out that I'm being an ass, and I'm sorry for that. I've just gotten frustrated with the relatively low amount of care that people have been putting into their pull requests lately, and you came in at a bad time. I shouldn't be discouraging you from experimenting and trying to stay involved.

**Comment by d4l3k** [comment]
I know how you feel. I really love the project by the way. It's awesome.

**Pull request merged**
